linters:
  enable-all: true
  disable:
    - cyclop
    - dogsled
    - errorlint
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - gocritic
    - godot
    - gomnd
    - lll
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

    #
    # Maybe fix later:
    #
    - goerr113
    - nilerr
    - nosnakecase
    - revive
    - stylecheck
    - tagliatelle

    #
    # Disabled because of generics:
    #
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    #
    # Disabled because deprecated:
    #
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - scopelint
    - varcheck

linters-settings:
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gosec:
    excludes:
     - G404 # Insecure random number source (rand)

output:
  print-issued-lines: true
  sort-results: true
