name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
          id: go

      - name: Check go mod is tidy
        run: |
          go mod tidy
          git diff-index HEAD
          git diff-index --quiet HEAD

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.2
      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2
      - name: Run golangci-lint
        run: golangci-lint run
